ALTER TYPE "TicketAutoOpenPeriodicity" ADD VALUE IF NOT EXISTS 'ONCE';
ALTER TYPE "TicketAutoOpenPeriodicity" ADD VALUE IF NOT EXISTS 'DAILY_WEEKDAYS';
ALTER TYPE "TicketAutoOpenPeriodicity" ADD VALUE IF NOT EXISTS 'BIWEEKLY';
ALTER TYPE "TicketAutoOpenPeriodicity" ADD VALUE IF NOT EXISTS 'BIMONTHLY';
ALTER TYPE "TicketAutoOpenPeriodicity" ADD VALUE IF NOT EXISTS 'QUARTERLY';
