import { expect, test } from "@playwright/test";
const png = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=", "base64");
test("images, reusable models and Excel/CSV work locally through the UI", async ({ page }) => {
  const projectCalls: string[] = [];
  await page.route("**/*", async (route) => {
    const url = new URL(route.request().url());
    if (url.pathname.endsWith("/auth/me")) return route.fulfill({ json: { user: { id: "demo-user", name: "Cliente Demo", email: "demo@example.test", role: "CLIENT_GESTOR", companyId: "demo-x", companyName: "Empresa Demo", firstAccess: false, permissions: [{ module: "PROJECTS", canView: true, canCreate: true, canEdit: true, canDelete: true, canApprove: false }] } } });
    if (route.request().resourceType() === "fetch" && /\/projetos\/(companies|projects|activities)/.test(url.pathname)) { projectCalls.push(url.pathname); return route.fulfill({ json: [] }); }
    return route.continue();
  });
  await page.goto("/projetos"); await page.getByRole("button", { name: "Demandas", exact: true }).click();
  await expect(page.getByText("Arraste as demandas para mudar de etapa.", { exact: false })).toHaveCount(0);
  await page.getByRole("button", { name: "Cartões", exact: true }).click();
  await expect(page.locator("article").getByRole("button", { name: "Subtarefa", exact: true })).toHaveCount(0);
  const card = await page.locator("article").first().boundingBox(); expect(card!.height).toBeLessThan(310);
  await page.getByRole("button", { name: "Nova demanda", exact: true }).click();
  await page.getByLabel("Título", { exact: true }).fill("Demanda com evidência visual");
  await page.getByLabel("Modelo da demanda", { exact: true }).selectOption({ label: "Análise de problema" });
  await page.getByRole("button", { name: "Aplicar modelo", exact: true }).click();
  await page.getByRole("button", { name: "Confirmar modelo", exact: true }).click();
  await expect(page.getByRole("textbox", { name: "Descrição", exact: true })).toContainText("Critérios de aceite");
  await page.getByLabel("Imagem da descrição", { exact: true }).setInputFiles({ name: "evidencia.png", mimeType: "image/png", buffer: png });
  await expect(page.getByRole("textbox", { name: "Descrição", exact: true }).locator("img")).toHaveCount(1);
  await page.getByRole("textbox", { name: "Descrição", exact: true }).press("Control+End");
  await page.keyboard.press("Enter"); await page.keyboard.insertText("Observação preservada ao alterar os campos.");
  await page.getByLabel("Solicitante", { exact: true }).fill("Equipe do piloto");
  await page.getByLabel("Etiquetas", { exact: true }).fill("piloto,validacao");
  await page.getByRole("button", { name: "Salvar demanda", exact: true }).click();
  await page.getByRole("button", { name: "Editar DEM-16", exact: true }).click();
  await expect(page.getByRole("textbox", { name: "Descrição", exact: true }).locator("img")).toHaveCount(1);
  await expect(page.getByRole("textbox", { name: "Descrição", exact: true })).toContainText("Observação preservada");
  await expect(page.getByLabel("Criado por", { exact: true })).toHaveValue("Cliente Demo");
  await expect(page.getByLabel("Tipo da demanda", { exact: true })).toHaveValue("BUG");
  await page.screenshot({ path: test.info().outputPath("rich-issue.png"), fullPage: true });
  await page.getByRole("button", { name: "Cancelar", exact: true }).click();
  await page.getByRole("button", { name: "Modelos de demandas", exact: true }).click();
  await page.getByRole("button", { name: "Novo modelo", exact: true }).click();
  await page.getByLabel("Nome do modelo", { exact: true }).fill("Modelo QA");
  await page.getByLabel("Imagem da descrição", { exact: true }).setInputFiles({ name: "modelo.png", mimeType: "image/png", buffer: png });
  await expect(page.getByRole("textbox", { name: "Descrição", exact: true }).locator("img")).toHaveCount(1);
  await page.getByRole("button", { name: "Salvar modelo", exact: true }).click();
  await expect(page.getByRole("button", { name: "Editar Modelo QA", exact: true })).toBeVisible();
  const modelsDownload = page.waitForEvent("download"); await page.getByRole("button", { name: "Exportar modelos", exact: true }).click();
  const models = await modelsDownload, modelPath = test.info().outputPath("modelos.json"); await models.saveAs(modelPath);
  await page.getByLabel("Arquivo de modelos", { exact: true }).setInputFiles(modelPath);
  await page.getByRole("button", { name: "Confirmar modelos", exact: true }).click();
  await expect(page.getByRole("button", { name: "Editar Modelo QA", exact: true })).toHaveCount(2);
  await page.getByRole("button", { name: "Close", exact: true }).click();
  const excelDownload = page.waitForEvent("download"); await page.getByRole("button", { name: "Exportar Excel", exact: true }).click();
  const excel = await excelDownload, excelPath = test.info().outputPath("demandas.xlsx"); await excel.saveAs(excelPath);
  const csvDownload = page.waitForEvent("download"); await page.getByRole("button", { name: "Exportar CSV", exact: true }).click();
  const csv = await csvDownload, csvPath = test.info().outputPath("demandas.csv"); await csv.saveAs(csvPath);
  await page.getByLabel("Arquivo de demandas", { exact: true }).setInputFiles(excelPath);
  await expect(page.getByRole("heading", { name: "Importar 16 demandas", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Confirmar importação", exact: true }).click();
  await expect(page.getByText("32 de 32 demandas", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Editar DEM-32", exact: true }).click();
  await expect(page.getByRole("textbox", { name: "Descrição", exact: true }).locator("img")).toHaveCount(1);
  await page.getByRole("button", { name: "Cancelar", exact: true }).click();
  await page.getByLabel("Arquivo de demandas", { exact: true }).setInputFiles(csvPath);
  await page.getByRole("button", { name: "Confirmar importação", exact: true }).click();
  await expect(page.getByText("48 de 48 demandas", { exact: true })).toBeVisible();
  await page.reload(); await page.getByRole("button", { name: "Demandas", exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 }); await page.getByRole("button", { name: "Cartões", exact: true }).click();
  await page.getByLabel("Buscar demandas", { exact: true }).fill("evidência visual");
  await expect(page.locator("article")).toHaveCount(3);
  await page.screenshot({ path: test.info().outputPath("compact-mobile.png"), fullPage: true });
  expect(projectCalls).toEqual([]);
});
