import { expect, test } from "@playwright/test";

test("mock issue hierarchy, inverse links, avatars and responsive custom columns", async ({ page }) => {
  const calls: string[] = [];
  await page.route("**/*", async (route) => {
    const url = new URL(route.request().url());
    if (url.pathname.endsWith("/auth/me")) return route.fulfill({ json: { user: { id: "demo-user", name: "Cliente Demo", email: "demo@example.test", role: "CLIENT_MEMBER", companyId: "demo-x", companyName: "Empresa Demo", firstAccess: false, permissions: [{ module: "PROJECTS", canView: true, canCreate: true, canEdit: true, canDelete: true, canApprove: false }] } } });
    if (route.request().resourceType() === "fetch" && /\/projetos\/(companies|projects|activities)/.test(url.pathname)) { calls.push(url.pathname); return route.fulfill({ json: [] }); }
    return route.continue();
  });
  await page.goto("/projetos");
  await page.getByRole("button", { name: "Demandas", exact: true }).click();
  await expect(page.getByText("15 de 15 demandas")).toBeVisible();
  await expect(page.locator("article select")).toHaveCount(0);
  await page.getByRole("button", { name: "Cartões", exact: true }).click();
  const issue1 = page.locator("article").filter({ has: page.getByRole("button", { name: "Preparar migração do ambiente de homologação", exact: true }) });
  await issue1.getByRole("button", { name: "Atribuir responsável DEM-1", exact: true }).click();
  await page.getByLabel("Buscar usuário", { exact: true }).fill("Bianca");
  await page.getByRole("button", { name: /Bianca Torres/ }).click();
  await expect(issue1.getByRole("button", { name: "Atribuir responsável DEM-1", exact: true })).toHaveAttribute("title", "Bianca Torres");
  await issue1.getByRole("button", { name: "Editar DEM-1", exact: true }).click();
  await page.getByRole("button", { name: "Criar subtarefa", exact: true }).click();
  await page.getByLabel("Título", { exact: true }).fill("Validar checklist de entrega");
  await expect(page.getByRole("combobox", { name: "Subtarefa de", exact: true })).toHaveValue(/issue-0$/);
  await page.getByRole("button", { name: "Salvar demanda", exact: true }).click();
  await page.getByRole("button", { name: "Editar DEM-16", exact: true }).click();
  const blocks = page.locator("details").filter({ has: page.locator("summary").filter({ hasText: /^Bloqueia / }) });
  await blocks.locator("summary").click();
  await blocks.getByLabel(/DEM-5 ·/).check();
  await page.getByRole("button", { name: "Salvar demanda", exact: true }).click();
  await page.getByRole("button", { name: "Kanban", exact: true }).click();
  await expect(page.locator("article").filter({ has: page.getByRole("button", { name: "Atualizar roteiro de operação assistida", exact: true }) })).toContainText("É bloqueada por: DEM-16");
  await page.getByRole("button", { name: "Nova coluna", exact: true }).click();
  await page.getByLabel("Nome da coluna", { exact: true }).fill("Aguardando aceite");
  await page.getByRole("combobox", { name: "Etapa do cronograma", exact: true }).selectOption("REVIEW");
  await page.getByRole("button", { name: "Salvar coluna", exact: true }).click();
  await page.getByRole("button", { name: "Editar DEM-16", exact: true }).click();
  await page.getByRole("combobox", { name: "Status", exact: true }).selectOption({ label: "Aguardando aceite" });
  await page.getByRole("button", { name: "Salvar demanda", exact: true }).click();
  await page.getByRole("button", { name: "Kanban", exact: true }).click();
  const column = page.getByRole("region", { name: "Coluna Aguardando aceite", exact: true });
  await expect(column).toContainText("Validar checklist de entrega");
  const handle = page.getByRole("separator", { name: "Redimensionar Aguardando aceite", exact: true });
  await handle.focus(); await handle.press("ArrowRight");
  await expect(handle).toHaveAttribute("aria-valuenow", "324");
  await handle.scrollIntoViewIfNeeded();
  const box = await handle.boundingBox();
  await page.mouse.move(box!.x + box!.width / 2, box!.y + 20); await page.mouse.down(); await page.mouse.move(box!.x + box!.width / 2 + 60, box!.y + 20, { steps: 5 }); await page.mouse.up();
  await expect(handle).toHaveAttribute("aria-valuenow", "384");
  await page.reload(); await page.getByRole("button", { name: "Demandas", exact: true }).click();
  await expect(page.getByRole("separator", { name: "Redimensionar Aguardando aceite", exact: true })).toHaveAttribute("aria-valuenow", "384");
  await page.screenshot({ path: test.info().outputPath("kanban-v2.png"), fullPage: true });
  await page.getByRole("button", { name: "Cronogramas", exact: true }).click();
  await page.getByRole("link").filter({ hasText: "Modernização da infraestrutura" }).click();
  await expect(page.getByRole("cell", { name: /Validar checklist de entrega/ }).first()).toBeVisible({ timeout: 30000 });
  await expect(page.getByRole("link", { name: "Cronogramas", exact: true })).not.toHaveClass(/underline/);
  await page.getByRole("button", { name: "Demandas", exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole("button", { name: "Cartões", exact: true }).click();
  await page.getByLabel("Buscar demandas", { exact: true }).fill("Validar checklist");
  await expect(page.locator("article")).toHaveCount(1);
  await page.screenshot({ path: test.info().outputPath("mobile-v2.png"), fullPage: true });
  await page.getByRole("button", { name: "Excluir DEM-16", exact: true }).click();
  await page.getByRole("button", { name: "Excluir demanda", exact: true }).click();
  await expect(page.locator("article")).toHaveCount(0);
  await page.goto("/projetos/foreign-company");
  await expect(page.getByText("Projeto ou empresa indisponível para o seu usuário.")).toBeVisible();
  expect(calls).toEqual([]);
});
