"use client";
import { useRef, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { IssueDescriptionEditor, type IssueDescriptionHandle } from "@/components/projetos/issue-description-editor";
import { ISSUE_TYPES, type IssueTemplate } from "@/lib/issue-templates";
import { readIssueTemplatesExcel, writeIssueTemplatesExcel } from "@/lib/issue-excel";
import { descriptionSections } from "@/lib/issue-description";
import { triggerBrowserDownload } from "@/lib/download-blob";
export function IssueTemplateManager({ companyId, templates, onSave, onDelete, onImport }: { companyId: string; templates: IssueTemplate[]; onSave: (template: IssueTemplate) => void; onDelete: (id: string) => void; onImport: (templates: IssueTemplate[]) => void }) {
  const [open, setOpen] = useState(false), [draft, setDraft] = useState<IssueTemplate | null>(null), [error, setError] = useState(""), [pending, setPending] = useState<IssueTemplate[] | null>(null), [deleting, setDeleting] = useState<string | null>(null), [busy, setBusy] = useState(false);
  const editor = useRef<IssueDescriptionHandle>(null), fileInput = useRef<HTMLInputElement>(null);
  return <><Button size="sm" variant="outline" onClick={() => { setOpen(true); setError(""); }}>Modelos de demandas</Button>
    <Dialog open={open} onOpenChange={(value) => { if (!busy) { setOpen(value); if (!value) setDraft(null); } }}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-3xl"><DialogHeader><DialogTitle>Modelos de demandas</DialogTitle><DialogDescription>Salve estruturas e campos padrão para reutilizar nas demandas da empresa.</DialogDescription></DialogHeader>
      {draft ? <form className="space-y-4" onSubmit={async (e) => { e.preventDefault(); setBusy(true); try { const description = await editor.current!.read(); onSave({ ...draft, description }); setDraft(null); setError(""); } catch (err) { setError(err instanceof Error ? err.message : "Falha ao salvar."); } finally { setBusy(false); } }}>
        <label className="block text-sm">Nome do modelo<Input required maxLength={100} value={draft.name} onChange={(e) => setDraft({ ...draft, name: e.target.value })} /></label>
        <div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Tipo padrão<select aria-label="Tipo padrão" className="h-9 w-full rounded-md border bg-background px-2" value={draft.issueType} onChange={(e) => setDraft({ ...draft, issueType: e.target.value as IssueTemplate["issueType"] })}>{Object.entries(ISSUE_TYPES).map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label><label className="text-sm">Departamento padrão<Input value={draft.department} onChange={(e) => setDraft({ ...draft, department: e.target.value })} /></label></div>
        <IssueDescriptionEditor key={draft.id} ref={editor} initialValue={draft.description} disabled={busy} />
        <div className="flex justify-end gap-2"><Button type="button" variant="outline" disabled={busy} onClick={() => setDraft(null)}>Cancelar</Button><Button type="submit" disabled={busy}>Salvar modelo</Button></div>
      </form> : <><div className="flex flex-wrap gap-2"><Button onClick={() => { setError(""); setDraft({ id: crypto.randomUUID(), companyId, name: "", description: descriptionSections("Descrição/Problema/Etc"), issueType: "TASK", priority: "MEDIUM", department: "", labels: [] }); }}>Novo modelo</Button><Button variant="outline" disabled={busy} onClick={() => fileInput.current?.click()}>Importar modelos</Button><Button variant="outline" disabled={busy || !templates.length} onClick={async () => { setBusy(true); try { const buffer = await writeIssueTemplatesExcel(templates); triggerBrowserDownload(new Blob([buffer], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" }), "modelos-demandas.xlsx"); setError(""); } catch (err) { setError(err instanceof Error ? err.message : "Falha ao exportar modelos."); } finally { setBusy(false); } }}>Exportar modelos</Button></div>
        <input ref={fileInput} type="file" accept=".xlsx" aria-label="Planilha de modelos" className="sr-only" onChange={async (e) => { const file = e.target.files?.[0]; e.target.value = ""; if (!file) return; setBusy(true); try { const items = await readIssueTemplatesExcel(await file.arrayBuffer(), companyId, () => crypto.randomUUID()); setPending(items); setError(""); } catch (err) { setError(err instanceof Error ? err.message : "Planilha de modelos inválida."); } finally { setBusy(false); } }} />
        <p className="text-xs text-muted-foreground">Importe ou exporte modelos em Excel.</p>
        <div className="space-y-2">{templates.map((t) => <div className="flex flex-wrap items-center justify-between gap-2 rounded-lg border p-3" key={t.id}><span className="text-sm font-medium">{t.name}</span><div className="flex gap-2"><Button size="sm" variant="ghost" onClick={() => { setError(""); setDraft({ ...t }); }}>Editar {t.name}</Button><Button size="sm" variant="ghost" disabled={busy} onClick={async () => { setBusy(true); try { const buffer = await writeIssueTemplatesExcel([t]); triggerBrowserDownload(new Blob([buffer], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" }), `modelo-${t.name.toLocaleLowerCase("pt-BR").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "demanda"}.xlsx`); setError(""); } catch (err) { setError(err instanceof Error ? err.message : "Falha ao exportar modelo."); } finally { setBusy(false); } }}>Exportar</Button><Button size="sm" variant="ghost" onClick={() => setDeleting(t.id)}>Excluir</Button></div></div>)}</div>
        {pending && <div className="space-y-2 rounded-lg border p-3"><p className="text-sm">Adicionar {pending.length} modelos: {pending.map((t) => t.name).join(", ")}</p><Button size="sm" onClick={() => { try { onImport(pending); setPending(null); } catch (err) { setError(err instanceof Error ? err.message : "Falha ao importar."); } }}>Confirmar modelos</Button><Button size="sm" variant="ghost" onClick={() => setPending(null)}>Cancelar</Button></div>}
        {deleting && <div className="rounded-lg border p-3"><p className="mb-2 text-sm">Excluir o modelo? As demandas já criadas serão preservadas.</p><Button size="sm" variant="destructive" onClick={() => { try { onDelete(deleting); setDeleting(null); } catch (err) { setError(err instanceof Error ? err.message : "Falha ao excluir."); } }}>Excluir modelo</Button><Button size="sm" variant="ghost" onClick={() => setDeleting(null)}>Cancelar</Button></div>}
      </>}{error && <p role="alert" className="text-sm text-destructive">{error}</p>}
    </DialogContent></Dialog>
  </>;
}
